// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJa34dLw5UG4pUERHuTClsABe4DKapjb4',
    appId: '1:659457059633:web:345c1c1aab01222decde10',
    messagingSenderId: '659457059633',
    projectId: 'learntrack-75e9c',
    authDomain: 'learntrack-75e9c.firebaseapp.com',
    storageBucket: 'learntrack-75e9c.firebasestorage.app',
    measurementId: 'G-Y5LQYQSKR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqqXJyxtu1NZhcRllcy9k65mGMuY6xRnE',
    appId: '1:659457059633:android:31336d76da038f83ecde10',
    messagingSenderId: '659457059633',
    projectId: 'learntrack-75e9c',
    storageBucket: 'learntrack-75e9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkvhcy1eGlcS_XFNhN-0uWZ1BYcndIMK8',
    appId: '1:659457059633:ios:54d6bdc4fc1d49b9ecde10',
    messagingSenderId: '659457059633',
    projectId: 'learntrack-75e9c',
    storageBucket: 'learntrack-75e9c.firebasestorage.app',
    iosBundleId: 'com.example.learntrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkvhcy1eGlcS_XFNhN-0uWZ1BYcndIMK8',
    appId: '1:659457059633:ios:54d6bdc4fc1d49b9ecde10',
    messagingSenderId: '659457059633',
    projectId: 'learntrack-75e9c',
    storageBucket: 'learntrack-75e9c.firebasestorage.app',
    iosBundleId: 'com.example.learntrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJa34dLw5UG4pUERHuTClsABe4DKapjb4',
    appId: '1:659457059633:web:4d4433c2d851dcfcecde10',
    messagingSenderId: '659457059633',
    projectId: 'learntrack-75e9c',
    authDomain: 'learntrack-75e9c.firebaseapp.com',
    storageBucket: 'learntrack-75e9c.firebasestorage.app',
    measurementId: 'G-DC9VF311VQ',
  );

}